# Generated by Django 5.2.6 on 2025-10-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.category')),
            ],
            options={
                'ordering': ('category_id', 'position'),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='menu_items', through='catalogs.ItemCategory', through_fields=('menu_item', 'category'), to='catalogs.category')),
            ],
            options={
                'ordering': ('restaurant_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.option')),
            ],
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='menu_items', through='catalogs.ItemOption', through_fields=('menu_item', 'option'), to='catalogs.option'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='catalogs.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('menu_item', 'category'), name='unique_menuitem_category'),
        ),
        migrations.AddConstraint(
            model_name='itemoption',
            constraint=models.UniqueConstraint(fields=('menu_item', 'option'), name='unique_menuitem_option'),
        ),
    ]
